set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-o

# Mouse Support On
 set -g mouse on

# split window

bind-key * split-window -h

# act like vim
bind-key l select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Multan"
set -g @dracula-show-fahrenheit false
set -g @dracula-plugins "weather"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
