# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131414)
$foreground = rgb(F2CCD0)
$color0 = rgb(3A3B3C)
$color1 = rgb(0F1519)
$color2 = rgb(26324C)
$color3 = rgb(214046)
$color4 = rgb(346B74)
$color5 = rgb(37717B)
$color6 = rgb(A3525C)
$color7 = rgb(E4AEB4)
$color8 = rgb(9F797E)
$color9 = rgb(141C21)
$color10 = rgb(324365)
$color11 = rgb(2C555E)
$color12 = rgb(458F9B)
$color13 = rgb(4997A4)
$color14 = rgb(D96D7A)
$color15 = rgb(E4AEB4)
